main/blog/urls.py
from django.conf.urls import patterns, url
from myktj import views
from django.views.decorators.csrf import csrf_exempt


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'ktj14.views.home', name='home'),
    url(r'^$', 'blog.views.thengakola')
)

main/main/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

admin.autodiscover()

urlpatterns = patterns('',
    # ('^sitemap.xml$', TemplateView.as_view(template_name = "sitemap.xml")),
    url(r'^', include('index.urls')),
    url(r'^accounts/', include('myktj.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^eventreg/',include('event.urls')),
    url(r'^kronicle/',include('blog.urls')),
    # url(r'^accounts/', include('myktj.urls')),
    # url(r'^api/', include('api.urls')),
)
urlpatterns += staticfiles_urlpatterns()

main/myktj/forms.py
from django import forms
from django.contrib.auth.models import User as User
from django.db import transaction
from django.forms.extras.widgets import SelectDateWidget
from django.forms import ModelForm
from django.contrib.auth import authenticate, login 
from django.utils import timezone
from myktj.models import * 
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import ugettext_lazy as _
from django.http.response import HttpResponseRedirect, HttpResponse

BIRTH_YEAR_CHOICES = [str(year) for year in range(1980, 2011)]

GENDER_CHOICES = (('M','Male'),
                  ('F','Female'))
                
YEAR_CHOICES = (('1','1st'),
                ('2','2nd'),
                ('3','3rd'),
                ('4','4th'),
                ('5','5th'),
                ('6','Postgraduate Ist'),
                ('7','Postgraduate IInd'),
                ('8','Postgraduate IIIrd'),
                ('9','Other'))

STATES = {'':'Choose State'}

INSTITUTES = {'':'Choose Institute'}

DEPARTMENTS = {}

class ProfileForm(forms.Form):
    username = forms.CharField(max_length = 30, label = _('Username'), required = True)
    email = forms.EmailField(max_length = 75, label = _('Email Address'), required = True)
    password1 = forms.CharField(label = _('Password'), required = False, widget = forms.PasswordInput)
    password2 = forms.CharField(label = _('Password(again)'), required = False, widget = forms.PasswordInput)
    firstname = forms.CharField(max_length = 30, label = _('Firstname'), required = True)
    lastname = forms.CharField(max_length = 30,label = _('Lastname'), required = True)
    gender = forms.ChoiceField(choices = GENDER_CHOICES, label = _('Gender'))
    dateOfBirth = forms.DateField(label = _('Date Of Birth'), widget = SelectDateWidget(years = BIRTH_YEAR_CHOICES))
    institution = forms.ChoiceField(choices = INSTITUTES, label = _('Institution'))
    country = forms.CharField(max_length = 100, label = _('Country'))
    state = forms.ChoiceField(choices = STATES, label = _('State'))
    department = forms.ChoiceField(choices = DEPARTMENTS, label = _('Department'))
    year = forms.ChoiceField(choices = YEAR_CHOICES, label = _('Year'))
    contact = forms.CharField(max_length = 20, label = _('Contact'))
    address = forms.CharField(label = _('Address'), widget = forms.Textarea)
    
    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)

        ss = State.objects.all()
        for s in ss:
            STATES[s.state]=s.state

        iis = Institute.objects.all()
        for ii in iis:
           INSTITUTES[ii.institute]=ii.institute
            
        ds = Department.objects.all()
        for d in ds:
            DEPARTMENTS[d.department]=d.department

        self.fields['state'].choices = STATES.items()
        self.fields['institution'].choices = INSTITUTES.items()
        self.fields['department'].choices = DEPARTMENTS.items()
        
    def clean(self):
        cleaned_data = super(ProfileForm, self).clean()
        print len(cleaned_data)
        if len(cleaned_data) == 15:
            u = User.objects.filter(username = self.cleaned_data['username'])
            if u.count() >= 1:
                raise forms.ValidationError(_("Username Exists, please try with another username."))

            u = User.objects.filter(email = self.cleaned_data['email'])
            if u.count() >= 1:
                raise forms.ValidationError(_("User with this Email ID Exists."))

            if self.cleaned_data['password1'] != self.cleaned_data['password2']:
                raise forms.ValidationError(_("Passwords are not matching."))

            if len(self.cleaned_data['password1']) < 6:
                raise forms.ValidationError(_("Password must be atleast 6 characters long."))
            return self.cleaned_data
        else:
            raise forms.ValidationError(_("All fields are mandatory."))
            return self.cleaned_data
 
    @transaction.commit_on_success
    def save(self):
        if self.is_valid():
            user = User.objects.create_user(self.cleaned_data['username'], self.cleaned_data['email'], self.cleaned_data['password1'])
            user.first_name = self.cleaned_data['firstname']
            user.last_name = self.cleaned_data['lastname']
            user.save()
            profile = Profile()
            profile.user = user
            profile.gender = self.cleaned_data['gender']
            profile.dateOfBirth = self.cleaned_data['dateOfBirth']
            profile.institute = Institute.objects.get(institute = self.cleaned_data['institution'])
            profile.country = self.cleaned_data['country']
            profile.state = State.objects.get(state = self.cleaned_data['state'])
            profile.department = Department.objects.get(department = self.cleaned_data['department'])
            profile.year = self.cleaned_data['year']
            profile.contact = self.cleaned_data['contact']
            profile.address = self.cleaned_data['address']
            profile.regDate = timezone.now()
            profile.save()

class LoginForm(forms.Form):
    username = forms.CharField(label = _("Username"), required = True)
    password = forms.CharField(label = _('Password'), required = True, widget = forms.PasswordInput)
    remember = forms.BooleanField(label = _("Remember Me"), required = False)
    user = None
    
    def clean(self):
        cleaned_data = super(LoginForm, self).clean()
        if self.is_valid():
            user = authenticate(username = self.cleaned_data['username'], password = self.cleaned_data['password'])
            if user:
                if user.is_active:
                    self.user = user
                else:
                    raise forms.ValidationError(_("This account is currently inactive"))
            else:
                raise forms.ValidationError(_('Incorrect credentials provided'))
            return self.cleaned_data
        raise forms.ValidationError(_("All fields are mandatory"))
    
    def get_success_url(self):
        return '/accounts/check_logged'
    
    def get_fail_url(self):
        return '/accounts/login'
    
    def login(self, request, redirect_url = None):
        user = self.user
        if user is not None:
            if user.is_active:
                login(request, user)
                ret = self.get_success_url()
            else:
                ret = self.get_fail_url()
        else:
            ret = self.get_fail_url()
        if self.cleaned_data["remember"]:
            request.session.set_expiry(60 * 60 * 24 * 7 * 3)
        else:
            request.session.set_expiry(0)
        return HttpResponseRedirect(ret)

main/templates/register_login/login.html
{% load url from future %}
{% load i18n %}
{% load static%}

{% block content %}
<div id="login_ktj_logo">
    <img src="{% static 'images/menu/ktj_logo.png' %}">
</div>
<div id="login-center">
    <div id="login_circle">
        <img src="{% static 'images/menu/user_icon.png' %}">
        <form id="login_form">
        {% csrf_token%}
            <div class="login-line" id="login-line-user">
                <span class="login-labels">{{ form.username.label }}</span>
                {{ form.username }}
            </div>
            <div class="login-line" id="login-line-pass">
                <span class="login-labels">{{ form.password.label }}</span>
                {{ form.password }}
            </div>
            <div class="login-line" id="login-line-pass">
                <span class="login-labels">{{ form.remember.label }}</span>
                {{ form.remember }}
            </div>
            <div class="login-line">
                <div onclick="login()" name="login-submit" class="login-submit" style="cursor:pointer;">SIGN-IN</div>
            </div>
        </form>
    </div>
    {% if form.errors %}
        <div class="error" style="color:white; font-family:Ubuntu-Condensed; font-size:16px;">Please provide valid crednetials.</div>
    {% endif %}
    <div id="register-login">
        <div class="register-login-box" onclick="openRegfromLogin();">
            SIGNUP
        </div>
    </div>
</div>
<div id="login_kgp_logo">
    <img src="{% static 'images/menu/kgp_logo.png' %}">
    <img src="{% static 'images/spons/home.png' %}" alt="" class="home-login" onclick="closeLogin();" />
</div>
{% endblock %}

main/templates/register_login/profile.html
{% load url from future %}
{% load i18n %}
{% load static%}

{% block content %}
<div class="reg_heading">
    <img src="{% static 'images/spons/home.png' %}" alt="" class="home-login" onclick="closeLogin();" style="margin: 10px 10px; cursor:pointer; float:left;" />
    <span style="font-size: 20px;">You are logged in.</span>
    <div id="logout" class="user-logout-box" onclick="logout();">Logout</div>
</div>
<div id="profile_display" class="scroll">
<div class="profile-section">
    <div class="profile-wrap">
        <div class="label">Username</div> 
        <div class="profile-element">{{user.username}}</div>
    </div>
    <div class="profile-wrap">
        <div class="label">Email</div> 
        <div class="profile-element">{{user.email}}</div>
    </div>
    <div class="profile-wrap">
        <div class="label">Password</div> 
        <div class="profile-element">*****</div>
    </div>
</div>
<div class="profile-section">
    <div class="profile-wrap">
        <div class="label">Name</div> 
        <div class="profile-element">{{ user.first_name }}{{ user.last_name }}</div>
    </div>
    <div class="profile-wrap">
        <div class="label">Gender</div> 
        <div class="profile-element">{{ profile.gender }}</div>
    </div>
    <div class="profile-wrap">
        <div class="label">Date Of Birth</div> 
        <div class="profile-element">{{ profile.dateOfBirth }}</div>
    </div>
    <div class="profile-wrap">
        <div class="label">Contact</div> 
        <div class="profile-element">{{ profile.contact }}</div>
    </div>
</div>
<div class="profile-section">
    <div class="profile-wrap">
        <div class="label">Country</div> 
        <div class="profile-element">{{ profile.country }}</div>
    </div>
    <div class="profile-wrap">
        <div class="label">State</div> 
        <div class="profile-element">{{ profile.state }}</div>
    </div>
    <div class="profile-wrap">
        <div class="label">Department</div> 
        <div class="profile-element">{{ profile.department }}</div>
    </div>
    <div class="profile-wrap">
        <div class="label"><label for="id_firstname">Year</label></div> 
        <div class="profile-element">{{ profile.year }}</div>
    </div>
</div>

<div class="profile-section">
    <div class="profile-wrap">
        <div class="label">Institution</div> 
        <div class="profile-element">{{ profile.institute }}</div>
    </div>
    <div class="profile-wrap">
        <div class="label">Address</div> 
        <div class="profile-element">{{ profile.address }}</div>
    </div>
    <div class="profile-wrap">
    </div>
</div>
</div>

{% endblock %}

main/templates/register_login/signup.html
{% load url from future %}
{% load i18n %}
{% load static%}
   
{% block content %}
<div class="reg_heading">
    <span>Register</span>
    <img src="{% static 'images/spons/home.png' %}" alt="" class="home-register" onclick="closeRegister()" />
</div>

<form class="signup" id="signup_form" method="post" action="{% url 'account_signup' %}">
    {% csrf_token%}
	<div class="register-section">
		<div class="register-wrap">
	        <div class="label">Name</div> 
	        <div class="input-element">{{ form.firstname }}{{ form.lastname }}</div>
	    </div>
	    <div class="register-wrap">
	        <div class="label">{{ form.username.label }}</div> 
	        <div class="input-element" id="username-input">{{ form.username }}</div>
	    </div>
	    
	    <div class="register-wrap">
	        <div class="label">{{ form.password1.label }}</div> 
	        <div class="input-element">{{ form.password1 }}</div>
	    </div>
	    <div class="register-wrap">
	        <div class="label">{{ form.password2.label }}</div> 
	        <div class="input-element">{{ form.password2 }}</div>
	    </div>
	    <div class="register-wrap">
	        <div class="label">{{ form.email.label }}</div> 
	        <div class="input-element" id="email-input">{{ form.email }}</div>
	    </div>
	    <div class="register-wrap">
	        <div class="label">{{ form.contact.label }}</div> 
	        <div class="input-element">{{ form.contact }}</div>
	    </div>
	</div>

	<div class="register-section">    
	<div class="register-wrap">
	    <div class="label">{{ form.gender.label }}</div> 
	    <div class="input-element">{{ form.gender }}</div>
	</div>
	<div class="register-wrap">
	    <div class="label">{{ form.dateOfBirth.label }}</div> 
	    <div class="input-element">{{ form.dateOfBirth}}</div>
	</div>
	<div class="register-wrap">
	    <div class="label">{{ form.country.label }}</div> 
	    <div class="input-element">{{ form.country }}</div>
	</div>
	<div class="register-wrap">
	    <div class="label">{{ form.state.label }}</div> 
	    <div class="scroll input-element">{{ form.state }}</div>
	</div>
	<div class="register-wrap">
	    <div class="label">{{ form.department.label }}</div> 
	    <div class="scroll input-element" style="width:90%;">{{ form.department }}</div>
	</div>
	<div class="register-wrap">
	    <div class="label"><label for="id_firstname">{{ form.year.label }}</label></div> 
	    <div class="scroll input-element">{{ form.year }}</div>
	</div>
	</div>  

	<div class="register-section">
        <div class="register-wrap" style="width:100%;">
            <div class="label">{{ form.institution.label }}</div> 
            <div class="scroll input-element">{{ form.institution }}</div>
        </div>
        <div class="register-wrap">
            <div class="label">{{ form.address.label }}</div> 
            <div class="input-element">{{ form.address }}</div>
        </div>
        <div class="register-wrap errors">
        {% if form.errors %}
			<div class="error">{{form.non_field_errors}}</div>
		{% endif %}
		</div>
		<div class="register-wrap">
  		    <div class="input-element">
	            <button type="button" onclick="signup()" class="signup_click">Signup</button>
	        </div>
  		</div>
	</div>
</form>
{% endblock %}